'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srWebZip
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://webzip.testing/", ConfigurationName:="srWebZip.WebZipSoap")>  _
    Public Interface WebZipSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webzip.testing/GetDataSet", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDataSet() As System.Data.DataSet
        
        'CODEGEN: Parameter 'GetDataSetAsByteArrayResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://webzip.testing/GetDataSetAsByteArray", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDataSetAsByteArray(ByVal request As srWebZip.GetDataSetAsByteArrayRequest) As srWebZip.GetDataSetAsByteArrayResponse
        
        'CODEGEN: Parameter 'GetDataSetAsByteArrayPlusResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://webzip.testing/GetDataSetAsByteArrayPlus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDataSetAsByteArrayPlus(ByVal request As srWebZip.GetDataSetAsByteArrayPlusRequest) As srWebZip.GetDataSetAsByteArrayPlusResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataSetAsByteArray", WrapperNamespace:="http://webzip.testing/", IsWrapped:=true)>  _
    Partial Public Class GetDataSetAsByteArrayRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataSetAsByteArrayResponse", WrapperNamespace:="http://webzip.testing/", IsWrapped:=true)>  _
    Partial Public Class GetDataSetAsByteArrayResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://webzip.testing/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public GetDataSetAsByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataSetAsByteArrayResult() As Byte)
            MyBase.New
            Me.GetDataSetAsByteArrayResult = GetDataSetAsByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataSetAsByteArrayPlus", WrapperNamespace:="http://webzip.testing/", IsWrapped:=true)>  _
    Partial Public Class GetDataSetAsByteArrayPlusRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataSetAsByteArrayPlusResponse", WrapperNamespace:="http://webzip.testing/", IsWrapped:=true)>  _
    Partial Public Class GetDataSetAsByteArrayPlusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://webzip.testing/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public GetDataSetAsByteArrayPlusResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataSetAsByteArrayPlusResult() As Byte)
            MyBase.New
            Me.GetDataSetAsByteArrayPlusResult = GetDataSetAsByteArrayPlusResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebZipSoapChannel
        Inherits srWebZip.WebZipSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebZipSoapClient
        Inherits System.ServiceModel.ClientBase(Of srWebZip.WebZipSoap)
        Implements srWebZip.WebZipSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetDataSet() As System.Data.DataSet Implements srWebZip.WebZipSoap.GetDataSet
            Return MyBase.Channel.GetDataSet
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srWebZip_WebZipSoap_GetDataSetAsByteArray(ByVal request As srWebZip.GetDataSetAsByteArrayRequest) As srWebZip.GetDataSetAsByteArrayResponse Implements srWebZip.WebZipSoap.GetDataSetAsByteArray
            Return MyBase.Channel.GetDataSetAsByteArray(request)
        End Function
        
        Public Function GetDataSetAsByteArray() As Byte()
            Dim inValue As srWebZip.GetDataSetAsByteArrayRequest = New srWebZip.GetDataSetAsByteArrayRequest()
            Dim retVal As srWebZip.GetDataSetAsByteArrayResponse = CType(Me,srWebZip.WebZipSoap).GetDataSetAsByteArray(inValue)
            Return retVal.GetDataSetAsByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srWebZip_WebZipSoap_GetDataSetAsByteArrayPlus(ByVal request As srWebZip.GetDataSetAsByteArrayPlusRequest) As srWebZip.GetDataSetAsByteArrayPlusResponse Implements srWebZip.WebZipSoap.GetDataSetAsByteArrayPlus
            Return MyBase.Channel.GetDataSetAsByteArrayPlus(request)
        End Function
        
        Public Function GetDataSetAsByteArrayPlus() As Byte()
            Dim inValue As srWebZip.GetDataSetAsByteArrayPlusRequest = New srWebZip.GetDataSetAsByteArrayPlusRequest()
            Dim retVal As srWebZip.GetDataSetAsByteArrayPlusResponse = CType(Me,srWebZip.WebZipSoap).GetDataSetAsByteArrayPlus(inValue)
            Return retVal.GetDataSetAsByteArrayPlusResult
        End Function
    End Class
End Namespace
